"""Bakes modifier mask coverage bitmaps into src/shared/maskData.ts.

Core gameplay: modifiers are paint MASKS (Factory-Balls style). While a
modifier is worn, the slime pixels it covers are protected from paint. The
client renders this with real image compositing; win detection and server
replay both need the same geometry WITHOUT a canvas — so this script samples
each modifier PNG's alpha channel onto a coarse grid and bakes the resulting
bitsets into shared TypeScript.

Usage:  python scripts/generate_masks.py

All source PNGs are 256x256 RGBA on a shared canvas (they composite by
plain stacking), so grid cell (x, y) means the same slime spot in every mask.
"""

import base64
import os

from PIL import Image

GRID = 64            # grid cells per side (64x64 = 4096 cells)
SRC = 256            # source PNG size
BLOCK = SRC // GRID  # pixels per cell side
# A cell counts as covered when its average alpha clears this bar. 100 (~40%)
# includes translucent goggle/glass lenses — lenses protect the band in
# Factory Balls, and SlimeRenderer flattens mask alpha with the SAME threshold
# when erasing paint so the visual result matches the sim.
THRESHOLD = 100

ASSET_DIR = os.path.join(os.path.dirname(__file__), '..', 'public', 'assets')
OUT_PATH = os.path.join(os.path.dirname(__file__), '..', 'src', 'shared', 'maskData.ts')

# Mask id -> asset path. Phaser texture key is always `mod-{id}`.
MASKS = {
    'goggles-h-thick': 'modifiers/horizontal-goggles-thick.png',
    'goggles-h-thin':  'modifiers/horizontal-goggles-thin.png',
    'goggles-h-mono':  'modifiers/horizontal-goggle.png',
    'goggles-v-thick': 'modifiers/vertical-goggles-thick.png',
    'goggles-v-thin':  'modifiers/vertical-goggles-thin.png',
    'goggles-v-mono':  'modifiers/vertical-goggle.png',
    'glasses-h-thick': 'modifiers/horizontal-glasses-thick.png',
    'glasses-h-thin':  'modifiers/horizontal-glasses-thin.png',
    'glasses-v-thick': 'modifiers/vertical-glasses-thick.png',
    'glasses-v-thin':  'modifiers/vertical-glasses-thin.png',
    'belt-h-thick':    'modifiers/horizontal-belt-thick.png',
    'belt-h-thin':     'modifiers/horizontal-belt-thin.png',
    'belt-v-thick':    'modifiers/vertical-belt-thick.png',
    'belt-v-thin':     'modifiers/vertical-belt-thin.png',
    'pendant-h':       'modifiers/horizontal-pendent.png',
    'pendant-v':       'modifiers/vertical-pendent.png',
    'pumpkin-25':      'modifiers/pumpkin-25.png',
    'pumpkin-50':      'modifiers/pumpkin-50.png',
    'pumpkin-75':      'modifiers/pumpkin-75.png',
    'underwear':       'modifiers/underwear.png',
}

BODY = 'slime/color.png'


def sample_bits(path: str) -> bytearray:
    im = Image.open(os.path.join(ASSET_DIR, path)).convert('RGBA')
    if im.size != (SRC, SRC):
        raise SystemExit(f'{path}: expected {SRC}x{SRC}, got {im.size}')
    alpha = im.getchannel('A').load()
    bits = bytearray((GRID * GRID + 7) // 8)
    for gy in range(GRID):
        for gx in range(GRID):
            total = 0
            for py in range(gy * BLOCK, (gy + 1) * BLOCK):
                for px in range(gx * BLOCK, (gx + 1) * BLOCK):
                    total += alpha[px, py]
            if total / (BLOCK * BLOCK) >= THRESHOLD:
                idx = gy * GRID + gx
                bits[idx >> 3] |= 1 << (idx & 7)
    return bits


def popcount(bits: bytearray) -> int:
    return sum(bin(b).count('1') for b in bits)


def overlap(a: bytearray, b: bytearray) -> int:
    return sum(bin(x & y).count('1') for x, y in zip(a, b))


def row_span(bits: bytearray) -> str:
    rows = [gy for gy in range(GRID)
            if any(bits[(gy * GRID + gx) >> 3] & (1 << ((gy * GRID + gx) & 7)) for gx in range(GRID))]
    if not rows:
        return 'empty'
    return f'rows {rows[0]}-{rows[-1]} of {GRID}'


def main() -> None:
    body = sample_bits(BODY)
    body_cells = popcount(body)
    masks = {mid: sample_bits(path) for mid, path in MASKS.items()}

    print(f'body: {body_cells} cells, {row_span(body)}')
    for mid, bits in masks.items():
        on_body = overlap(bits, body)
        print(f'{mid:18s} covers {on_body:4d} body cells ({100 * on_body / body_cells:4.1f}%)  {row_span(bits)}')

    lines = [
        '// AUTO-GENERATED by scripts/generate_masks.py - DO NOT EDIT BY HAND.',
        '// Regenerate with:  python scripts/generate_masks.py',
        '//',
        '// Coverage bitsets sampled from the modifier PNG alpha channels on a',
        f'// {GRID}x{GRID} grid over the shared 256x256 slime canvas. Bit (y * GRID + x)',
        '// is set when that cell is covered (average alpha >= ' + str(THRESHOLD) + '). Shared by the',
        '// client engine and the server replay so both simulate identical paint',
        '// protection without touching a canvas.',
        '',
        f'export const MASK_GRID = {GRID};',
        '',
        '// Cells that belong to the slime body itself (from slime/color.png) —',
        '// only these cells participate in pattern comparison.',
        f"export const BODY_MASK = '{base64.b64encode(bytes(body)).decode()}';",
        '',
        '// Keyed by mask id; the matching Phaser texture key is `mod-{id}`.',
        'export const MASK_BITMAPS: Record<string, string> = {',
    ]
    for mid, bits in masks.items():
        lines.append(f"  '{mid}': '{base64.b64encode(bytes(bits)).decode()}',")
    lines.append('};')
    lines.append('')

    with open(OUT_PATH, 'w', newline='\n', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print(f'wrote {os.path.relpath(OUT_PATH)}')


if __name__ == '__main__':
    main()
